export * from "./component_controller/horarios.controller.js";
export * from "./component_controller/crear.controller.js";
export * from "./component_controller/imagenes.controller.js";
export * from "./component_controller/obtener.controller.js";
export * from "./component_controller/actualizar.controller.js";
export * from "./component_controller/eliminar.controller.js";
export * from "./component_controller/estados.controller.js";
export * from "./component_controller/consultas.controller.js";
export * from "./component_controller/reportes.controller.js";
